### ISSUE TITLE
500 przy "Przejdź do realizacji zamówienia" kiedy klient nie ma konta

### ISSUE THREAD

**Issue by Olafejs** [pay-now/paynow-prestashop#186]
![Zrzut ekranu 2023-07-17 o 12 25 33](https://github.com/pay-now/paynow-prestashop/assets/11058593/07b2d3f2-2d64-4f0a-a99e-efb95d53ef3d)

Jeśli klient nie ma konta i wybierze produkt i później w koszyku naciśnie "Przejdź do realizacji zamówienia" wyrzuca białą stronę i 500. Po wyłączeniu modułu Paynow, Prestashop działa prawidłowo.

Moduł działa prawidłowo również jak klient ma konto i jest zalogowany.

Error Log:
`Fatal error: Uncaught TypeError: PrestaShop\PrestaShop\Core\Security\Hashing::hash(): Argument #1 ($passwd) must be of type string, null given, called in /home/XXX/ftp/sklep.weeball.pl/classes/Tools.php on line 1224 and defined in /home/XXX/ftp/sklep.weeball.pl/src/Core/Security/Hashing.php:31 Stack trace: #0 /home/XXX/ftp/sklep.weeball.pl/classes/Tools.php(1224): PrestaShop\PrestaShop\Core\Security\Hashing->hash(NULL, 'ndcx9hgvquzkrbx...') #1 /home/XXX/ftp/sklep.weeball.pl/classes/Tools.php(1210): ToolsCore::hash(NULL) #2 /home/XXX/ftp/sklep.weeball.pl/modules/paynow/classes/PaynowPaymentOptions.php(131): ToolsCore::encrypt(NULL) #3 /home/XXX/ftp/sklep.weeball.pl/modules/paynow/classes/PaynowPaymentOptions.php(104): PaynowPaymentOptions->setUpAdditionalTemplateVariables(Object(Paynow\Model\PaymentMethods\PaymentMethod)) #4 /home/XXX/ftp/sklep.weeball.pl/modules/paynow/paynow.php(402): PaynowPaymentOptions->generate() #5 /home/XXX/ftp/sklep.weeball.pl/classes/Hook.php(993): Paynow->hookPaymentOptions(Array) #6 /home/XXX/ftp/sklep.weeball.pl/classes/Hook.php(418): HookCore::coreCallHook(Object(Paynow), 'hookPaymentOpti...', Array) #7 /home/XXX/ftp/sklep.weeball.pl/classes/Hook.php(928): HookCore::callHookOn(Object(Paynow), 'paymentOptions', Array) #8 /home/XXX/ftp/sklep.weeball.pl/src/Adapter/HookManager.php(81): HookCore::exec('paymentOptions', Array, NULL, true, true, false, NULL) #9 /home/XXX/ftp/sklep.weeball.pl/src/PrestaShopBundle/Service/Hook/HookFinder.php(70): PrestaShop\PrestaShop\Adapter\HookManager->exec('paymentOptions', Array, NULL, true) #10 /home/XXX/ftp/sklep.weeball.pl/classes/checkout/PaymentOptionsFinder.php(56): PrestaShopBundle\Service\Hook\HookFinder->find() #11 /home/XXX/ftp/sklep.weeball.pl/classes/checkout/PaymentOptionsFinder.php(82): PaymentOptionsFinderCore->find() #12 /home/XXX/ftp/sklep.weeball.pl/classes/checkout/CheckoutPaymentStep.php(83): PaymentOptionsFinderCore->present(false) #13 /home/XXX/ftp/sklep.weeball.pl/src/Core/Foundation/Templating/RenderableProxy.php(52): CheckoutPaymentStepCore->render(Array) #14 /home/XXX/ftp/sklep.weeball.pl/config/smartyfront.config.inc.php(100): PrestaShop\PrestaShop\Core\Foundation\Templating\RenderableProxy->render(Array) #15 /home/XXX/ftp/sklep.weeball.pl/classes/Smarty/SmartyLazyRegister.php(81): smartyRender(Array, Object(SmartyDevTemplate)) #16 /home/XXX/ftp/sklep.weeball.pl/var/cache/dev/smarty/compile/22/29/08/22290837513f90cd31c5ee1e570c1c816b17cb7c_2.file.checkout-process.tpl.php(29): SmartyLazyRegister->__call('smartyRender', Array) #17 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_64b5156f095417_45895866(Object(SmartyDevTemplate)) #18 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(SmartyDevTemplate)) #19 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(SmartyDevTemplate)) #20 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 0) #21 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(SmartyDevTemplate), NULL, NULL, NULL, 0) #22 /home/XXX/ftp/sklep.weeball.pl/classes/Smarty/SmartyDevTemplate.php(55): Smarty_Internal_TemplateBase->fetch(NULL, NULL, NULL, NULL) #23 /home/XXX/ftp/sklep.weeball.pl/classes/checkout/CheckoutProcess.php(162): SmartyDevTemplateCore->fetch() #24 /home/XXX/ftp/sklep.weeball.pl/src/Core/Foundation/Templating/RenderableProxy.php(52): CheckoutProcessCore->render(Array) #25 /home/XXX/ftp/sklep.weeball.pl/config/smartyfront.config.inc.php(100): PrestaShop\PrestaShop\Core\Foundation\Templating\RenderableProxy->render(Array) #26 /home/XXX/ftp/sklep.weeball.pl/classes/Smarty/SmartyLazyRegister.php(81): smartyRender(Array, Object(SmartyDevTemplate)) #27 /home/XXX/ftp/sklep.weeball.pl/var/cache/dev/smarty/compile/classiclayouts_layout_full_width_tpl/1a/b0/bb/1ab0bb656db248ddd240a0dc53e8dc1c616467f5_2.file.checkout.tpl.php(70): SmartyLazyRegister->__call('smartyRender', Array) #28 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(248): Block_154076482964b5156eec9e24_89555853->callBlock(Object(SmartyDevTemplate)) #29 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance->callBlock(Object(Block_154076482964b5156eec9e24_89555853), Object(SmartyDevTemplate)) #30 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(156): Smarty_Internal_Runtime_Inheritance->process(Object(SmartyDevTemplate), Object(Block_154076482964b5156eec9e24_89555853)) #31 /home/XXX/ftp/sklep.weeball.pl/var/cache/dev/smarty/compile/classiclayouts_layout_full_width_tpl/1a/b0/bb/1ab0bb656db248ddd240a0dc53e8dc1c616467f5_2.file.checkout.tpl.php(112): Smarty_Internal_Runtime_Inheritance->instanceBlock(Object(SmartyDevTemplate), 'Block_154076482...', 'checkout_proces...', 0) #32 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(248): Block_8233787664b5156eec9c60_24018983->callBlock(Object(SmartyDevTemplate)) #33 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance->callBlock(Object(Block_8233787664b5156eec9c60_24018983), Object(SmartyDevTemplate)) #34 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(186): Smarty_Internal_Runtime_Inheritance->process(Object(SmartyDevTemplate), Object(Block_8233787664b5156eec9c60_24018983), Object(Block_209580162464b5156256bee4_60763492)) #35 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(156): Smarty_Internal_Runtime_Inheritance->process(Object(SmartyDevTemplate), Object(Block_209580162464b5156256bee4_60763492)) #36 /home/XXX/ftp/sklep.weeball.pl/var/cache/dev/smarty/compile/classiclayouts_layout_full_width_tpl/2f/85/10/2f8510e734a1954d1bdb45d16ec60b1d7de81560_2.file.layout-full-width.tpl.php(101): Smarty_Internal_Runtime_Inheritance->instanceBlock(Object(SmartyDevTemplate), 'Block_209580162...', 'content', 1) #37 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(248): Block_120862245564b5156256b4c6_76148782->callBlock(Object(SmartyDevTemplate)) #38 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance->callBlock(Object(Block_120862245564b5156256b4c6_76148782), Object(SmartyDevTemplate)) #39 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(186): Smarty_Internal_Runtime_Inheritance->process(Object(SmartyDevTemplate), Object(Block_120862245564b5156256b4c6_76148782), Object(Block_202282406464b51562584403_14712042)) #40 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(156): Smarty_Internal_Runtime_Inheritance->process(Object(SmartyDevTemplate), Object(Block_202282406464b51562584403_14712042)) #41 /home/XXX/ftp/sklep.weeball.pl/var/cache/dev/smarty/compile/classiclayouts_layout_full_width_tpl/84/b6/04/84b604ddeea0d609acb7c06157af41349b4be6f7_2.file.layout-both-columns.tpl.php(94): Smarty_Internal_Runtime_Inheritance->instanceBlock(Object(SmartyDevTemplate), 'Block_202282406...', 'content_wrapper') #42 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_64b51562586bd3_05151786(Object(SmartyDevTemplate)) #43 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(SmartyDevTemplate)) #44 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(SmartyDevTemplate)) #45 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render() #46 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(116): Smarty_Internal_Template->_subTemplateRender('layouts/layout-...', NULL, 'classiclayouts/...', 0, 3600, Array, 2, false, NULL, NULL) #47 /home/XXX/ftp/sklep.weeball.pl/var/cache/dev/smarty/compile/classiclayouts_layout_full_width_tpl/2f/85/10/2f8510e734a1954d1bdb45d16ec60b1d7de81560_2.file.layout-full-width.tpl.php(42): Smarty_Internal_Runtime_Inheritance->endChild(Object(SmartyDevTemplate), 'layouts/layout-...') #48 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_64b5156256c4f8_95911539(Object(SmartyDevTemplate)) #49 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(SmartyDevTemplate)) #50 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(SmartyDevTemplate)) #51 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render() #52 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(116): Smarty_Internal_Template->_subTemplateRender('layouts/layout-...', NULL, 'classiclayouts/...', 0, 3600, Array, 2, false, NULL, NULL) #53 /home/XXX/ftp/sklep.weeball.pl/var/cache/dev/smarty/compile/classiclayouts_layout_full_width_tpl/1a/b0/bb/1ab0bb656db248ddd240a0dc53e8dc1c616467f5_2.file.checkout.tpl.php(46): Smarty_Internal_Runtime_Inheritance->endChild(Object(SmartyDevTemplate), 'layouts/layout-...') #54 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_64b5156eecb3d6_07258275(Object(SmartyDevTemplate)) #55 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(SmartyDevTemplate)) #56 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(SmartyDevTemplate)) #57 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 0) #58 /home/XXX/ftp/sklep.weeball.pl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(SmartyDevTemplate), NULL, 'classiclayouts/...', NULL, 0) #59 /home/XXX/ftp/sklep.weeball.pl/classes/Smarty/SmartyDev.php(40): Smarty_Internal_TemplateBase->fetch('checkout/checko...', NULL, 'classiclayouts/...', NULL) #60 /home/XXX/ftp/sklep.weeball.pl/classes/controller/FrontController.php(715): SmartyDev->fetch('checkout/checko...', NULL, 'classiclayouts/...') #61 /home/XXX/ftp/sklep.weeball.pl/classes/controller/FrontController.php(697): FrontControllerCore->smartyOutputContent('checkout/checko...') #62 /home/XXX/ftp/sklep.weeball.pl/classes/controller/Controller.php(339): FrontControllerCore->display() #63 /home/XXX/ftp/sklep.weeball.pl/classes/Dispatcher.php(510): ControllerCore->run() #64 /home/XXX/ftp/sklep.weeball.pl/index.php(28): DispatcherCore->dispatch() #65 {main} thrown in /home/XXX/ftp/sklep.weeball.pl/src/Core/Security/Hashing.php on line 31`

**Comment by Olafejs** [comment]
Żeby klienci mogli kupować do czasu naprawy błędu rozwiązaniem tymczasowym jest:

zamiana w `themes/classic/templates/checkout/_partials/cart-detailed-actions.tpl`

z:

`<div class="text-sm-center">
        <a href="{$urls.pages.order}" class="btn btn-primary">{l s='Proceed to checkout' d='Shop.Theme.Actions'}</a>
        {hook h='displayExpressCheckout'}
      </div>`

na:

`{if $customer.is_logged}
        <div class="text-sm-center">
          <a href="{$urls.pages.order}" class="btn btn-primary">{l s='Proceed to checkout' d='Shop.Theme.Actions'}</a>
          {hook h='displayExpressCheckout'}
        </div>
      {else}
        <div class="text-sm-center">
          <a href="{$urls.pages.register}" class="btn btn-primary">{l s='Załóż konto' d='Shop.Theme.Actions'}</a>
        </div>
      {/if}`

Zmiana powoduje że niezalogowany użytkownik nie może przejść do realizacji, jest przekierowywany najpierw do założenia konta.

**Comment by shado80** [comment]
Ja niestety mam ten problem na prestashop 8.1 także dla zarejestrowanych klientów.

**Comment by shado80** [comment]
> to samo, kiedy wsparcie dla wersji PS 8.1 @emilleszczak2 ?

Z najnowszą wersją dalej nie działa? Już mi się nawet nie chce sprawdzać. Minęło pół roku i dalej kicha. Chcąc nie chcąc musiałem przejść do konkurencji, bo tam po prostu działa. Czy poza przelewy24 jest jeszcze jakaś wtyczka działająca z PS8.1?
